server:
  port: 8081
  tomcat:
    basedir: D:\\temp
#################################
## DATASOURCE
#################################

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fss
    username: root
    password: root
  redis:
      database: 5
      host: 192.168.1.161
      port: 6379
      timeout: 50000
      password: 201805
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 64
        # 连接池中的最大空闲连接
        max-idle: 64
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 1
